Upgrade to Play 2.3.6
The AccessLog class was using SimpleResult which was removed in Play 2.3 and resulted
in a NoClassDefFoundError on usage, see https://playframework.com/documentation/2.3.x/Migration23